# Generated by Django 4.1.7 on 2023-03-30 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_car_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='license_plate',
            field=models.CharField(max_length=10, null=True, unique=True, verbose_name='Гос_номер'),
        ),
    ]
